# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4fd2c8157a6f357686df9be80991d23845e03f603bcf74d8d2fe3b818a0ddba7bcb69720b3a25f6d2de11fa3af02e58572123a44bfa66d60c7da700816666e4b

test:
  secret_key_base: 7eb512cd12f05602d79fce59f04de0ef4afbb6e2791e98055a7cbacd040ecfe13ae48409569255598e2a69adcb4436ecdf7fd89e073751b37d2105345016ed64

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
